# Generated by Django 6.1.1 on 2026-09-09 21:05

import user.managers
import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="first name"),
                ),
                (
                    "first_surname",
                    models.CharField(max_length=150, verbose_name="first surname"),
                ),
                (
                    "second_surname",
                    models.CharField(max_length=150, verbose_name="second surname"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                ("city", models.CharField(max_length=150, verbose_name="city")),
                (
                    "dni",
                    models.CharField(
                        help_text="Spanish national ID: 8 digits followed by a letter (e.g. 12345678Z).",
                        max_length=9,
                        unique=True,
                        validators=[user.validators.validate_dni],
                        verbose_name="DNI",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="date of birth")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="staff status"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("dni__regex", "^[0-9]{8}[A-Za-z]$")),
                        name="user_dni_valid_format",
                    )
                ],
            },
            managers=[
                ("objects", user.managers.CustomUserManager()),
            ],
        ),
    ]
