[project]
name = "it-incidents-reporter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django==6.1.1",
]

[dependency-groups]
dev = [
    "django-stubs==6.1.0",
    "ipykernel==7.3.0",
    "mypy==2.3.1",
    "pdoc==16.0.0",
    "pytest==9.1.1",
    "pytest-django==4.14.0",
    "ruff==0.16.6",
]

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "incidents_reporter.settings"
