# Generated by Django 6.1.1 on 2026-09-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="archived"),
        ),
    ]
